services:

  site:
    image: cartosp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    ports:
      - "8000:8000"
    restart: unless-stopped