server {
        listen       8000;
        listen  [::]:8000;
        server_name  localhost;

        root   /usr/share/nginx/html;

        server_tokens off;
        sub_filter_once off;
        sub_filter random_nonce_value $request_id;
        sub_filter '<script>' '<script nonce="$request_id">';
        sub_filter '<style>' '<style nonce="$request_id">';

        location ~ /index.html|.*\.toml|.*\.json$ {
          expires -1;
          add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header Referrer-Policy strict-origin-when-cross-origin;
          add_header Permissions-Policy "geolocation=()";
          add_header Content-Security-Policy "default-src 'none';style-src 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-elem 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-attr 'unsafe-inline';script-src 'self' 'nonce-$request_id';script-src-elem 'self' 'nonce-$request_id';font-src 'self' data: https://cdn.jsdelivr.net;img-src 'self' data: https:;connect-src 'self' data.geopf.fr;base-uri 'self';form-action 'self';";
        }

        location ~ .*\.css$|.*\.js$ {
          add_header Cache-Control 'max-age=86400'; # 24h
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header Referrer-Policy strict-origin-when-cross-origin;
          add_header Permissions-Policy "geolocation=()";
          add_header Content-Security-Policy "default-src 'none';style-src 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-elem 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-attr 'unsafe-inline';script-src 'self' 'nonce-$request_id';script-src-elem 'self' 'nonce-$request_id';font-src 'self' data: https://cdn.jsdelivr.net;img-src 'self' data: https:;connect-src 'self' data.geopf.fr;base-uri 'self';form-action 'self';";
        }

        location ~ .*\.otf$|.*\.ttf$|.*\.woff2?$ {
          add_header Cache-Control 'max-age=31536000'; # 1year
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header Referrer-Policy strict-origin-when-cross-origin;
          add_header Permissions-Policy "geolocation=()";
          add_header Content-Security-Policy "default-src 'none';style-src 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-elem 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-attr 'unsafe-inline';script-src 'self' 'nonce-$request_id';script-src-elem 'self' 'nonce-$request_id';font-src 'self' data: https://cdn.jsdelivr.net;img-src 'self' data: https:;connect-src 'self' data.geopf.fr;base-uri 'self';form-action 'self';";
        }

        location / {
          try_files $uri $uri/ /index.html;

          add_header Cache-Control 'max-age=86400'; # 24h
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header Referrer-Policy strict-origin-when-cross-origin;
          add_header Permissions-Policy "geolocation=()";
          add_header Content-Security-Policy "default-src 'none';style-src 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-elem 'self' 'nonce-$request_id' https://cdn.jsdelivr.net;style-src-attr 'unsafe-inline';script-src 'self' 'nonce-$request_id';script-src-elem 'self' 'nonce-$request_id';font-src 'self' data: https://cdn.jsdelivr.net;img-src 'self' data: https:;connect-src 'self' data.geopf.fr;base-uri 'self';form-action 'self';";
        }

        error_page 401 403 404 405 408  /40x.html;
        location = /40x.html {
            return 302 /page-introuvable;
        }

        error_page   500 502 503 504 520 521 522  /50x.html;
        location = /50x.html {
            return 302 /erreur;
        }
}

